"""Add "AutoEdit" to DaVinci Resolve's Workspace > Scripts menu.

    python install_resolve_script.py
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

LAUNCHER = '''# AutoEdit launcher - generated by install_resolve_script.py
import sys
AUTOEDIT_HOME = {home!r}
if AUTOEDIT_HOME not in sys.path:
    sys.path.insert(0, AUTOEDIT_HOME)
from autoedit.gui import main
main(resolve_hint=globals())
'''


def scripts_dir() -> str:
    if sys.platform.startswith("win"):
        base = os.path.join(os.environ["APPDATA"], "Blackmagic Design",
                            "DaVinci Resolve", "Support", "Fusion")
    elif sys.platform == "darwin":
        base = os.path.expanduser("~/Library/Application Support/Blackmagic Design/"
                                  "DaVinci Resolve/Fusion")
    else:
        base = os.path.expanduser("~/.local/share/DaVinciResolve/Fusion")
    return os.path.join(base, "Scripts", "Edit")


def main() -> None:
    target_dir = scripts_dir()
    os.makedirs(target_dir, exist_ok=True)
    target = os.path.join(target_dir, "AutoEdit.py")
    with open(target, "w", encoding="utf-8") as f:
        f.write(LAUNCHER.format(home=HERE))
    print(f"Đã cài: {target}")
    print("Khởi động lại DaVinci Resolve, rồi vào trang Edit > "
          "Workspace > Scripts > AutoEdit.")


if __name__ == "__main__":
    main()
